### ISSUE TITLE
Default directory structure

### ISSUE THREAD

**Issue by dalance** [veryl-lang/veryl#1515]
Defining default directory structure and creating them by `veryl new` may be useful.
If almost all standalone projects have the same structure, it make easy to see them.
Users can customize it by necessary.

```toml
[build]
source = "src"
target = {type = "directory", path = "target"}
```

```
Veryl.toml
src/
target/
```
