### ISSUE TITLE
Can't resolve grandchild dependency specified by `path` field

### ISSUE THREAD

**Issue by taichi-ishitani** [veryl-lang/veryl#1699]
Veryl reports `MetadataError::FileNotFound` error if the grandchild dependency specified by using `path` field.

For example:

Directory structure
```
+-- a
|   +-- b
|   |   `-- Veryl.toml
|   +-- Veryl.toml
`-- c
    `-- Veryl.toml
```

Veryl.toml files

```toml
# a/Veryl.toml
...
[dependencies]
b = { path = "./b" }
```

```toml
# a/b/Veryl.toml
...
```

```toml
# c/Veryl.toml
...
[dependencies]
a = { path = "../a" }
```

* project `c` depends on project `a`.
* project `a` depends on project `a/b`.

Veryl reports `reports `MetadataError::FileNotFound` error when building project `c`.

```
[ishitani@pzserv8 c]
$ cat Veryl.toml
[project]
name = "c"
version = "0.1.0"
[build]
source = "src"
target = {type = "directory", path = "target"}
[dependencies]
a = { path = "../a" }
[ishitani@pzserv8 c]
$ veryl build
Error: MetadataError::FileNotFound

  × Veryl.toml is not found
  help:
```

[veryl.tar.gz](https://github.com/user-attachments/files/20623083/veryl.tar.gz)
