### ISSUE TITLE
Allow to specify multiple source directories

### ISSUE THREAD

**Issue by taichi-ishitani** [veryl-lang/veryl#1746]
Currently, only one directory can be specified on the `source` field of the `Veryl.toml` but multiple directories can't be specified.
To support such use case, the `sources` fieild should be added.

```toml
[bould]
sources = ["rtl", "tb"]
```
