### ISSUE TITLE
[Feature] Global properties like `define macro`

### ISSUE THREAD

**Issue by taichi-ishitani** [veryl-lang/veryl#554]
SV's `define macro` is a useful feature for following porposes.

* Sharing properties globally
* Setting properties from external

I'd like Veryl to have such feature natively instead of preprocessor.

[Pkl](https://github.com/apple/pkl) has an accessor method to get env variables, properties set via the CLI switch, etc.
I prefer such feature.
https://pkl-lang.org/main/current/language-reference/index.html#resources

**Comment by taichi-ishitani** [comment]
Define properties in the `propeties` section like below.

```toml
[project]
name = "main"

[properties]
foo = "foo"
bar = 32
baz = true
```

Override them in the `dependencies` section.

```toml
[project]
name = "main"

[dependencies]
sub = {
    path = "{}",
    properties = { foo = "FOO", baz = true }
}
```
