### ISSUE TITLE
veryl-0.13.0 can't be built because of runaway builds

### ISSUE THREAD

**Issue by yurivict** [veryl-lang/veryl#975]
We have all amd64 builds failing because the Rust compiler doesn't produce an output, see the  [Ruust issue](https://github.com/rust-lang/rust/issues/130905).

Do you use any special options to build Veryl?

**Comment by dalance** [comment]
If the following profile doesn't effect, compilation time increase extremely.
Is this option is used in the build?

```toml
[profile.release]
# Workaround for long time compilation
# https://github.com/rust-lang/rust/issues/106211
codegen-units = 1
```

https://github.com/rust-lang/rust/issues/106211 seems to be fixed, but there is another issue: https://github.com/rust-lang/rust/issues/129776.

**Comment by dalance** [comment]
The `-C` options of the last command seems to contain `-C codegen-units=1`

```
-C opt-level=3 -C panic=abort -C linker-plugin-lto -C codegen-units=1 -C metadata=0edb5deee78252e7 -C extra-filename=-0edb5deee78252e7 -C linker=cc -C strip=debuginfo -C link-arg=-fstack-protector-strong`
```

The `-C` options of my local build log is below:

```
-C opt-level=3 -C embed-bitcode=no -C codegen-units=1 -C metadata=9d34c72853834718 -C extra-filename=-9d34c72853834718 -C linker=/usr/bin/cc -C strip=debuginfo
```

`-C linker-plugin-lto` is used in your environment only, and LTO is related to the compliation time issue.
So could you try to remove the `-C linker-plugin-lto`?

**Comment by yurivict** [comment]
The FreeBSD port didn't add linker-plugin-lto, and such string doesn't appear in the veryl sources.

**Comment by dalance** [comment]
Could you try the following profile?

```toml
[profile.release]
to = "off"
```
